[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
  "npm --prefix frontend install",
  "npm --prefix frontend run build",
  "mkdir -p backend/public",
  "cp -r frontend/dist/* backend/public/",
  "npm --prefix backend install",
  "npm --prefix backend run build"
]

[start]
cmd = "cd backend && npm start"